"use client";

import { FormEvent, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

export default function SetPassword(){
  const [ready,setReady]=useState(false); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{supabase?.auth.getSession().then(({data})=>{if(!data.session)setMessage("This invitation link is no longer active. Please ask your admin to send a new invitation.");setReady(true)})},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setBusy(true);setMessage("");const f=new FormData(e.currentTarget);const password=String(f.get("password"));const confirm=String(f.get("confirm"));if(password.length<8){setMessage("Use at least 8 characters.");setBusy(false);return}if(password!==confirm){setMessage("Passwords do not match.");setBusy(false);return}const {error}=await supabase.auth.updateUser({password,data:{invited:false}});if(error){setMessage(error.message);setBusy(false);return}window.location.href="/dashboard"}
  return <main className="grid min-h-screen place-items-center bg-[#f7f7f5] p-6"><div className="w-full max-w-md rounded-3xl border border-black/10 bg-white p-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#173b32] text-sm font-bold text-white">L</div><span className="text-xl font-semibold">loggin</span></div><h1 className="mt-10 text-3xl font-semibold">Set your password.</h1><p className="mt-3 text-sm leading-6 text-[#6b6b6b]">Your company invited you to Loggin. Choose the password you’ll use for future sign-ins.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-medium">Password<input required name="password" type="password" minLength={8} className="mt-2 w-full rounded-xl border border-black/10 px-3 py-3 outline-none focus:border-[#173b32]"/></label><label className="block text-sm font-medium">Confirm password<input required name="confirm" type="password" minLength={8} className="mt-2 w-full rounded-xl border border-black/10 px-3 py-3 outline-none focus:border-[#173b32]"/></label><button disabled={!ready||busy} className="w-full rounded-xl bg-[#173b32] py-3.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Set password & enter Loggin"}</button></form>{message&&<p className="mt-4 rounded-xl bg-[#f5f3ed] p-3 text-sm text-[#5d5a4f]">{message}</p>}</div></main>
}
