"use client";

import { FormEvent, useEffect, useState } from "react";
import { Eye, EyeOff } from "lucide-react";
import { supabase, supabaseConfigError } from "@/lib/supabase";

const DEMO_ACCOUNTS = [["Founder", "founder@loggin.test"], ["Admin", "admin@loggin.test"], ["Manager", "manager@loggin.test"], ["Employee", "employee@loggin.test"]] as const;
const DEMO_PASSWORD = "LogginDemo123!";

export default function Home() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => { if (data.session) window.location.href = "/"; }); }, []);
  function useDemo(value: string) { setEmail(value); setPassword(DEMO_PASSWORD); setError(null); }
  async function signIn(event: FormEvent) { event.preventDefault(); setError(null); if (!supabase) { setError(supabaseConfigError); return; } setLoading(true); const { error: authError } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); setLoading(false); if (authError) { setError(authError.message); return; } window.location.href = "/"; }
  return <main className="min-h-screen bg-neutral-950 text-white flex items-center justify-center p-6"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.04] p-8 shadow-2xl"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-cyan-300">Loggin</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Your company, right now.</h1><p className="mt-2 text-sm text-white/55">Founder-first attendance for modern teams.</p></div><form onSubmit={signIn} className="space-y-4"><input className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 outline-none focus:border-cyan-300/60" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Work email" required /><div className="relative"><input className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 pr-12 outline-none focus:border-cyan-300/60" type={showPassword ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" required /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(v => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-white/50 hover:bg-white/10 hover:text-white">{showPassword ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div>{error && <div className="rounded-2xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</div>}<button className="w-full rounded-2xl bg-cyan-300 px-4 py-3 font-semibold text-neutral-950 disabled:opacity-50" disabled={loading || !supabase}>{loading ? "Signing in…" : "Sign in"}</button></form><div className="mt-8 border-t border-white/10 pt-6"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-white/40">Local test accounts</p><div className="grid grid-cols-2 gap-2">{DEMO_ACCOUNTS.map(([role, accountEmail]) => <button key={accountEmail} type="button" onClick={() => useDemo(accountEmail)} className="rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-left hover:bg-white/10"><span className="block text-xs font-semibold text-cyan-300">{role}</span><span className="mt-1 block truncate text-xs text-white/55">{accountEmail}</span></button>)}</div><p className="mt-3 text-xs text-white/35">Click an account to fill its email and demo password.</p></div></div></main>;
}