"use client";

import { FormEvent, useState } from "react";
import { supabase, supabaseConfigError } from "@/lib/supabase";

export default function SignupPage() {
  const [fullName,setFullName]=useState(""); const [companyName,setCompanyName]=useState(""); const [email,setEmail]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function createWorkspace(e:FormEvent){e.preventDefault();setError("");setMessage("");if(!supabase){setError(supabaseConfigError??"Supabase is not configured.");return}setLoading(true);const {error:authError}=await supabase.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{shouldCreateUser:true,emailRedirectTo:`${window.location.origin}/auth/callback?next=/dashboard`,data:{full_name:fullName.trim(),company_name:companyName.trim()}}});setLoading(false);if(authError){setError(authError.message);return}setMessage("Check your email. Your secure Loggin workspace link is on its way.")}
  return <main className="min-h-screen bg-[#f7f7f5] p-6"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-5xl items-center justify-center"><div className="grid w-full overflow-hidden rounded-[2rem] border border-black/10 bg-white shadow-sm lg:grid-cols-[.9fr_1.1fr]"><section className="bg-[#173b32] p-8 text-white lg:p-12"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 font-bold">L</div><span className="text-xl font-semibold">loggin</span></div><div className="mt-20 max-w-sm"><p className="text-sm font-medium text-white/60">Attendance, without the admin headache.</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] lg:text-5xl">Create your workspace.</h1><p className="mt-5 text-sm leading-7 text-white/65">Start as the founder. Add your office, bring in your team, and let Loggin handle daily attendance.</p></div></section><section className="p-8 lg:p-12"><div className="flex items-center justify-between"><div><p className="text-sm text-[#6b6b6b]">New to Loggin?</p><h2 className="mt-1 text-2xl font-semibold">Create account</h2></div><a href="/" className="text-sm font-medium text-[#173b32]">Sign in</a></div><form onSubmit={createWorkspace} className="mt-8 space-y-4"><label className="block text-sm font-medium">Your name<input value={fullName} onChange={e=>setFullName(e.target.value)} required autoComplete="name" className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 outline-none focus:border-[#173b32]" placeholder="Your name" /></label><label className="block text-sm font-medium">Company name<input value={companyName} onChange={e=>setCompanyName(e.target.value)} required autoComplete="organization" className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 outline-none focus:border-[#173b32]" placeholder="Your company" /></label><label className="block text-sm font-medium">Work email<input value={email} onChange={e=>setEmail(e.target.value)} required type="email" autoComplete="email" className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 outline-none focus:border-[#173b32]" placeholder="you@company.com" /></label>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</div>}<button disabled={loading} className="w-full rounded-xl bg-[#173b32] py-3.5 text-sm font-semibold text-white disabled:opacity-50">{loading?"Sending secure link…":"Create workspace"}</button></form><p className="mt-6 text-xs leading-5 text-[#777]">No password to remember. We'll send a secure sign-in link to your work email.</p></section></div></div></main>;
}
